# 1. Basis-Image von nginx verwenden
FROM nginx:latest

# 2. Arbeitsverzeichnis im Container festlegen
WORKDIR /usr/share/nginx/html

# 3. Deine Webseite in den Container kopieren
COPY index.html .

# 4. Standardport von nginx wird automatisch genutzt (80)
